name: CI
on:
  pull_request:
  push:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            java: 8
          - os: ubuntu-latest
            java: 11
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: ${{ matrix.java }}
      - uses: sbt/setup-sbt@v1
      - name: Coursier cache
        uses: coursier/cache-action@v6
      - name: Build and test
        run: sbt scalafmtSbtCheck scalafmtCheckAll +test
      - run: rm -rf "$HOME/.ivy2/local" || true
